A README.md file is required.
> biokbase.narrative_method_store.baseclient.ServerError: JSONRPCError: -32500.
> /tmp/narrative_method_store_temp/github_1764950458927.temp/README.md (No such
> file or directory)